name       : mumble
version    : 1.2.19
release    : 16
source     :
    - https://github.com/mumble-voip/mumble/releases/download/1.2.19/mumble-1.2.19.tar.gz : f047fb707ad93948b0bc913ec0a89cd5480d87e840c4ff2519608fc8a2dac0e8
license    : BSD-3-Clause
component  : network.clients
summary    : High quality voice chat software
description: |
    Mumble is an open source, low-latency, high quality voice chat software primarily intended for use while gaming.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(avahi-compat-libdns_sd)
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(libpulse)
    - pkgconfig(opus)
    - pkgconfig(protobuf)
    - pkgconfig(QtCore)
    - pkgconfig(sndfile)
    - pkgconfig(speex)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - libboost-devel
    - libcap2-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-AudioOutput.patch
    qmake-qt4 -r main.pro CONFIG+="c++11 bundled-celt no-bundled-opus no-bundled-speex no-embed-qt-translations no-g15 no-speechd no-ice no-update" \
              QMAKE_MOC=/usr/bin/moc-qt4 \
              QMAKE_RCC=/usr/bin/rcc-qt4 \
              QMAKE_UIC=/usr/bin/uic-qt4
build      : |
    %make release
install    : |-
    %make_install
    # Credit to aur package: https://aur.archlinux.org/packages/mumble-git/

    install -m755 -D ./scripts/mumble-overlay %installroot%/usr/bin/mumble-overlay
    install -m755 -D ./release/mumble %installroot%/usr/bin/mumble
    install -m644 -D ./scripts/mumble.desktop %installroot%/usr/share/applications/mumble.desktop
    install -m755 -d %installroot%/usr/share/man/man1
    install -m644 -D ./man/mum* %installroot%/usr/share/man/man1/
    install -m644 -D ./icons/mumble.svg %installroot%/usr/share/icons/hicolor/scalable/apps/mumble.svg
    install -m644 -D ./LICENSE %installroot%/usr/share/licenses/mumble/LICENSE
    install -m755 -D ./release/plugins/liblink.so %installroot%/%libdir%/mumble/liblink.so
    install -m755 -D ./release/plugins/libmanual.so %installroot%/%libdir%/mumble/libmanual.so
    install -m755 -D ./release/libcelt* %installroot%/%libdir%/mumble/
