name       : mumble
version    : 1.4.287
release    : 34
source     :
    - https://github.com/mumble-voip/mumble/releases/download/v1.4.287/mumble-1.4.287.tar.gz : 378e61d5bfa58ba51bfbb645067f459214a9872da09b306f2c2c3f1902200547
license    : BSD-3-Clause
component  : network.clients
summary    : High quality voice chat software
description: |
    Mumble is an open source, low-latency, high quality voice chat software primarily intended for use while gaming.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(alsa)
    - pkgconfig(avahi-compat-libdns_sd)
    - pkgconfig(harfbuzz)
    - pkgconfig(libcap)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(opus)
    - pkgconfig(protobuf)
    - pkgconfig(sndfile)
    - pkgconfig(speex)
    - pkgconfig(xi)
    - libboost-devel
    - poco-devel
setup      : |
    %cmake_ninja \
        -Dbundled-opus=OFF \
        -Dbundled-speex=OFF \
        -Dbundle-qt-translations=OFF \
        -Dg15=OFF \
        -Dice=OFF \
        -Doverlay-xcompile=OFF \
        -Dserver=OFF \
        -Dspeechd=OFF \
        -Dupdate=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
