name       : mumble
# Note: We took from git and regen'd: 381109e0a341f83bc37b3270f1800c18e0c43d05
version    : 1.2.8
release    : 1
source     :
    - https://evolve-os.com/sources/mumble-1.2.8.tar.xz : f7247db6ed9d74528bbcf81616628582abdb4f9699f1ea0c53620ceb4c3d4e8b
license    : BSD-3-Clause
summary    : High quality voice chat software
description: |
    Mumble is an open source, low-latency, high quality voice chat software primarily intended for use while gaming.
builddeps  :
    - pkgconfig(Qt5Core)
    - qt5-translations
    - pkgconfig(avahi-compat-libdns_sd)
    - pkgconfig(protobuf)
    - pkgconfig(libpulse)
    - pkgconfig(sndfile)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - libboost-devel
setup      : |
    qmake -r main.pro CONFIG+="no-g15 no-speechd no-ice"
build      : |
    %make
install    : |
    %make_install
    # Credit to aur package: https://aur.archlinux.org/packages/mumble-git/
    
    install -m755 -D ./scripts/mumble-overlay %installroot%/usr/bin/mumble-overlay
    install -m755 -D ./release/mumble %installroot%/usr/bin/mumble
    install -m644 -D ./scripts/mumble.desktop %installroot%/usr/share/applications/mumble.desktop
    install -m755 -d %installroot%/usr/share/man/man1
    install -m644 -D ./man/mum* %installroot%/usr/share/man/man1/
    install -m644 -D ./icons/mumble.svg %installroot%/usr/share/icons/hicolor/scalable/apps/mumble.svg
    install -m644 -D ./LICENSE %installroot%/usr/share/licenses/mumble/LICENSE
    install -m755 -D ./release/plugins/liblink.so %installroot%/%libdir%/mumble/liblink.so
    install -m755 -D ./release/plugins/libmanual.so %installroot%/%libdir%/mumble/libmanual.so
    install -m755 -D ./release/libcelt* %installroot%/%libdir%/mumble/
