name       : mumble
version    : 1.3.4
release    : 27
source     :
    - git|https://github.com/mumble-voip/mumble.git : 1.3.4
license    : BSD-3-Clause
component  : network.clients
summary    : High quality voice chat software
description: |
    Mumble is an open source, low-latency, high quality voice chat software primarily intended for use while gaming.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(alsa)
    - pkgconfig(avahi-compat-libdns_sd)
    - pkgconfig(harfbuzz)
    - pkgconfig(libcap)
    - pkgconfig(libpulse)
    - pkgconfig(protobuf)
    - pkgconfig(sndfile)
    - pkgconfig(speex)
    - pkgconfig(xi)
    - libboost-devel
setup      : |
    %qmake CONFIG+="c++11 bundled-celt bundled-opus no-bundled-speex no-embed-qt-translations no-g15 no-ice no-server no-speechd no-update"
build      : |
    %make release
install    : |
    %make_install

    install -Dm00755 ./scripts/mumble-overlay $installdir/usr/bin/mumble-overlay
    install -Dm00755 ./release/mumble $installdir/usr/bin/mumble
    install -Dm00644 ./scripts/mumble.desktop $installdir/usr/share/applications/mumble.desktop
    install -Dm00644 ./man/mum* -t $installdir/usr/share/man/man1/
    install -Dm00644 ./icons/mumble.svg $installdir/usr/share/icons/hicolor/scalable/apps/mumble.svg
    install -Dm00755 ./release/plugins/*.so -t $installdir/%libdir%/mumble/
    install -Dm00755 ./release/*.so* -t $installdir/%libdir%/mumble/
