name       : mumble
version    : 1.3.0
release    : 17
source     :
    - https://github.com/mumble-voip/mumble/releases/download/1.3.0/mumble-1.3.0.tar.gz : 9a8de2547344962a81c00c37b5d8bd5a371bb685fa36cf03a3f134e37c79b80d
license    : BSD-3-Clause
component  : network.clients
summary    : High quality voice chat software
description: |
    Mumble is an open source, low-latency, high quality voice chat software primarily intended for use while gaming.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(avahi-compat-libdns_sd)
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(libpulse)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sndfile)
    - pkgconfig(speex)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - libboost-devel
    - libcap2-devel
setup      : |
    # Have set bundled-opus due to https://github.com/mumble-voip/mumble/issues/3547, lack of 1.3.x support
    %qmake CONFIG+="c++11 bundled-celt bundled-opus no-bundled-speex no-embed-qt-translations no-g15 no-ice no-server no-speechd no-update"
build      : |
    %make release
install    : |
    %make_install

    install -Dm00755 ./scripts/mumble-overlay $installdir/usr/bin/mumble-overlay
    install -Dm00755 ./release/mumble $installdir/usr/bin/mumble
    install -Dm00644 ./scripts/mumble.desktop $installdir/usr/share/applications/mumble.desktop
    install -Dm00644 ./man/mum* -t $installdir/usr/share/man/man1/
    install -Dm00644 ./icons/mumble.svg $installdir/usr/share/icons/hicolor/scalable/apps/mumble.svg
    install -Dm00755 ./release/plugins/*.so -t $installdir/%libdir%/mumble/
    install -Dm00755 ./release/*.so* -t $installdir/%libdir%/mumble/
